### ISSUE TITLE
Add /setup endpoint

### ISSUE THREAD

**Issue by iMicknl** [iMicknl/python-tahoma-api#189]
We currently don't use this in ha-tahoma, but it makes sense to have this endpoint in our API client as well. I use this a lot to retrieve full setup details of users I am helping.

**Comment by iMicknl** [comment]
@tetienne you are good in testing I saw lately. I have about 5 setup.jsons from different users (tahoma, hi kumo, nexity, cozy touch). Can we add them to the repo and do automatic testing? (I will obfuscate all information).

Eventually we could even use these setup.jsons to do end to end testing with our HA component.

**Comment by tetienne** [comment]
If this endpoint exists we can indeed add it. 
About testing, you can have a look of I've already done and just add a parameterized layee above to run your test with various json.
