### ISSUE TITLE
Full list of ui class

### ISSUE THREAD

**Issue by tetienne** [iMicknl/python-tahoma-api#3]
We found the full list of ui class [here](https://www.tahomalink.com/enduser-mobile-web/enduserAPI/doc/test/8ddc2d4dc206d573db9e99984a501056b4ad7f93ed772730ac7ed48ec0579214)

```
AdjustableSlatsRollerShutter
AirSensor
Alarm
Awning
Ballast
Camera
CarButtonSensor
CircuitBreaker
ConfigurationComponent
ConsumptionSensor
ContactSensor
Curtain
Dock
DoorLock
ElectricitySensor
EvoHome
ExteriorHeatingSystem
ExteriorScreen
ExteriorVenetianBlind
GarageDoor
GasSensor
Gate
Generic
GenericSensor
GroupConfiguration
HeatPumpSystem
HeatingSystem
HitachiHeatingSystem
HumiditySensor
IRBlasterController
IntrusionSensor
Light
LightSensor
MusicPlayer
NetworkComponent
OccupancySensor
OnOff
Oven
Pergola
Pod
ProtocolGateway
RainSensor
RemoteController
RollerShutter
Screen
Shutter
Siren
SmokeSensor
SunIntensitySensor
SunSensor
SwimmingPool
SwingingShutter
TemperatureSensor
ThermalEnergySensor
ThirdPartyGateway
VenetianBlind
VentilationSystem
WashingMachine
WaterHeatingSystem
WaterSensor
WeatherSensor
Wifi
WindSensor
Window
WindowHandle
```

We have to create an enum with these values.

**Comment by vlebourl** [comment]
Do we have to? shouldn't the api be generic? this info is also in each device. I'm not sure how we would use this enum.

**Comment by iMicknl** [comment]
I believe this is dynamic, thus I am not sure why an enum would add any value?

**Comment by tetienne** [comment]
Sorry for the delay. An Enum will allow to type our code. So instead of expecting a string, we will expect an enum. It will secure our code and help to find a potential bug with mypy.
